/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CompteRouteImport } from './routes/compte'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompteIndexRouteImport } from './routes/compte.index'
import { Route as ProfilHandleRouteImport } from './routes/profil.$handle'
import { Route as PlatIdRouteImport } from './routes/plat.$id'
import { Route as CompteRestaurateurRouteImport } from './routes/compte.restaurateur'
import { Route as CompteMesPlatsRouteImport } from './routes/compte.mes-plats'
import { Route as CompteDashboardRouteImport } from './routes/compte.dashboard'
import { Route as CompteContactRouteImport } from './routes/compte.contact'
import { Route as CompteConfidentialiteRouteImport } from './routes/compte.confidentialite'
import { Route as CompteAmisRouteImport } from './routes/compte.amis'
import { Route as CompteAideRouteImport } from './routes/compte.aide'
import { Route as CompteAbonnesRouteImport } from './routes/compte.abonnes'
import { Route as CompteAbonnementsRouteImport } from './routes/compte.abonnements'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push-dispatch'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRoute = CompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteIndexRoute = CompteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompteRoute,
} as any)
const ProfilHandleRoute = ProfilHandleRouteImport.update({
  id: '/profil/$handle',
  path: '/profil/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatIdRoute = PlatIdRouteImport.update({
  id: '/plat/$id',
  path: '/plat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompteRestaurateurRoute = CompteRestaurateurRouteImport.update({
  id: '/restaurateur',
  path: '/restaurateur',
  getParentRoute: () => CompteRoute,
} as any)
const CompteMesPlatsRoute = CompteMesPlatsRouteImport.update({
  id: '/mes-plats',
  path: '/mes-plats',
  getParentRoute: () => CompteRoute,
} as any)
const CompteDashboardRoute = CompteDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CompteRoute,
} as any)
const CompteContactRoute = CompteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CompteRoute,
} as any)
const CompteConfidentialiteRoute = CompteConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => CompteRoute,
} as any)
const CompteAmisRoute = CompteAmisRouteImport.update({
  id: '/amis',
  path: '/amis',
  getParentRoute: () => CompteRoute,
} as any)
const CompteAideRoute = CompteAideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => CompteRoute,
} as any)
const CompteAbonnesRoute = CompteAbonnesRouteImport.update({
  id: '/abonnes',
  path: '/abonnes',
  getParentRoute: () => CompteRoute,
} as any)
const CompteAbonnementsRoute = CompteAbonnementsRouteImport.update({
  id: '/abonnements',
  path: '/abonnements',
  getParentRoute: () => CompteRoute,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push-dispatch',
  path: '/api/public/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/compte': typeof CompteRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publier': typeof PublierRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/compte/abonnements': typeof CompteAbonnementsRoute
  '/compte/abonnes': typeof CompteAbonnesRoute
  '/compte/aide': typeof CompteAideRoute
  '/compte/amis': typeof CompteAmisRoute
  '/compte/confidentialite': typeof CompteConfidentialiteRoute
  '/compte/contact': typeof CompteContactRoute
  '/compte/dashboard': typeof CompteDashboardRoute
  '/compte/mes-plats': typeof CompteMesPlatsRoute
  '/compte/restaurateur': typeof CompteRestaurateurRoute
  '/plat/$id': typeof PlatIdRoute
  '/profil/$handle': typeof ProfilHandleRoute
  '/compte/': typeof CompteIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publier': typeof PublierRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/compte/abonnements': typeof CompteAbonnementsRoute
  '/compte/abonnes': typeof CompteAbonnesRoute
  '/compte/aide': typeof CompteAideRoute
  '/compte/amis': typeof CompteAmisRoute
  '/compte/confidentialite': typeof CompteConfidentialiteRoute
  '/compte/contact': typeof CompteContactRoute
  '/compte/dashboard': typeof CompteDashboardRoute
  '/compte/mes-plats': typeof CompteMesPlatsRoute
  '/compte/restaurateur': typeof CompteRestaurateurRoute
  '/plat/$id': typeof PlatIdRoute
  '/profil/$handle': typeof ProfilHandleRoute
  '/compte': typeof CompteIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/carte': typeof CarteRoute
  '/cgu': typeof CguRoute
  '/compte': typeof CompteRouteWithChildren
  '/confidentialite': typeof ConfidentialiteRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/publier': typeof PublierRoute
  '/recherche': typeof RechercheRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/compte/abonnements': typeof CompteAbonnementsRoute
  '/compte/abonnes': typeof CompteAbonnesRoute
  '/compte/aide': typeof CompteAideRoute
  '/compte/amis': typeof CompteAmisRoute
  '/compte/confidentialite': typeof CompteConfidentialiteRoute
  '/compte/contact': typeof CompteContactRoute
  '/compte/dashboard': typeof CompteDashboardRoute
  '/compte/mes-plats': typeof CompteMesPlatsRoute
  '/compte/restaurateur': typeof CompteRestaurateurRoute
  '/plat/$id': typeof PlatIdRoute
  '/profil/$handle': typeof ProfilHandleRoute
  '/compte/': typeof CompteIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/push-dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/cgu'
    | '/compte'
    | '/confidentialite'
    | '/mcp'
    | '/mentions-legales'
    | '/publier'
    | '/recherche'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/compte/abonnements'
    | '/compte/abonnes'
    | '/compte/aide'
    | '/compte/amis'
    | '/compte/confidentialite'
    | '/compte/contact'
    | '/compte/dashboard'
    | '/compte/mes-plats'
    | '/compte/restaurateur'
    | '/plat/$id'
    | '/profil/$handle'
    | '/compte/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/cgu'
    | '/confidentialite'
    | '/mcp'
    | '/mentions-legales'
    | '/publier'
    | '/recherche'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/compte/abonnements'
    | '/compte/abonnes'
    | '/compte/aide'
    | '/compte/amis'
    | '/compte/confidentialite'
    | '/compte/contact'
    | '/compte/dashboard'
    | '/compte/mes-plats'
    | '/compte/restaurateur'
    | '/plat/$id'
    | '/profil/$handle'
    | '/compte'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-dispatch'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/carte'
    | '/cgu'
    | '/compte'
    | '/confidentialite'
    | '/mcp'
    | '/mentions-legales'
    | '/publier'
    | '/recherche'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/assistant'
    | '/compte/abonnements'
    | '/compte/abonnes'
    | '/compte/aide'
    | '/compte/amis'
    | '/compte/confidentialite'
    | '/compte/contact'
    | '/compte/dashboard'
    | '/compte/mes-plats'
    | '/compte/restaurateur'
    | '/plat/$id'
    | '/profil/$handle'
    | '/compte/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/push-dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CarteRoute: typeof CarteRoute
  CguRoute: typeof CguRoute
  CompteRoute: typeof CompteRouteWithChildren
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  McpRoute: typeof McpRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PublierRoute: typeof PublierRoute
  RechercheRoute: typeof RechercheRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  PlatIdRoute: typeof PlatIdRoute
  ProfilHandleRoute: typeof ProfilHandleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte': {
      id: '/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof CompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/': {
      id: '/compte/'
      path: '/'
      fullPath: '/compte/'
      preLoaderRoute: typeof CompteIndexRouteImport
      parentRoute: typeof CompteRoute
    }
    '/profil/$handle': {
      id: '/profil/$handle'
      path: '/profil/$handle'
      fullPath: '/profil/$handle'
      preLoaderRoute: typeof ProfilHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plat/$id': {
      id: '/plat/$id'
      path: '/plat/$id'
      fullPath: '/plat/$id'
      preLoaderRoute: typeof PlatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compte/restaurateur': {
      id: '/compte/restaurateur'
      path: '/restaurateur'
      fullPath: '/compte/restaurateur'
      preLoaderRoute: typeof CompteRestaurateurRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/mes-plats': {
      id: '/compte/mes-plats'
      path: '/mes-plats'
      fullPath: '/compte/mes-plats'
      preLoaderRoute: typeof CompteMesPlatsRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/dashboard': {
      id: '/compte/dashboard'
      path: '/dashboard'
      fullPath: '/compte/dashboard'
      preLoaderRoute: typeof CompteDashboardRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/contact': {
      id: '/compte/contact'
      path: '/contact'
      fullPath: '/compte/contact'
      preLoaderRoute: typeof CompteContactRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/confidentialite': {
      id: '/compte/confidentialite'
      path: '/confidentialite'
      fullPath: '/compte/confidentialite'
      preLoaderRoute: typeof CompteConfidentialiteRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/amis': {
      id: '/compte/amis'
      path: '/amis'
      fullPath: '/compte/amis'
      preLoaderRoute: typeof CompteAmisRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/aide': {
      id: '/compte/aide'
      path: '/aide'
      fullPath: '/compte/aide'
      preLoaderRoute: typeof CompteAideRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/abonnes': {
      id: '/compte/abonnes'
      path: '/abonnes'
      fullPath: '/compte/abonnes'
      preLoaderRoute: typeof CompteAbonnesRouteImport
      parentRoute: typeof CompteRoute
    }
    '/compte/abonnements': {
      id: '/compte/abonnements'
      path: '/abonnements'
      fullPath: '/compte/abonnements'
      preLoaderRoute: typeof CompteAbonnementsRouteImport
      parentRoute: typeof CompteRoute
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-dispatch': {
      id: '/api/public/push-dispatch'
      path: '/api/public/push-dispatch'
      fullPath: '/api/public/push-dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CompteRouteChildren {
  CompteAbonnementsRoute: typeof CompteAbonnementsRoute
  CompteAbonnesRoute: typeof CompteAbonnesRoute
  CompteAideRoute: typeof CompteAideRoute
  CompteAmisRoute: typeof CompteAmisRoute
  CompteConfidentialiteRoute: typeof CompteConfidentialiteRoute
  CompteContactRoute: typeof CompteContactRoute
  CompteDashboardRoute: typeof CompteDashboardRoute
  CompteMesPlatsRoute: typeof CompteMesPlatsRoute
  CompteRestaurateurRoute: typeof CompteRestaurateurRoute
  CompteIndexRoute: typeof CompteIndexRoute
}

const CompteRouteChildren: CompteRouteChildren = {
  CompteAbonnementsRoute: CompteAbonnementsRoute,
  CompteAbonnesRoute: CompteAbonnesRoute,
  CompteAideRoute: CompteAideRoute,
  CompteAmisRoute: CompteAmisRoute,
  CompteConfidentialiteRoute: CompteConfidentialiteRoute,
  CompteContactRoute: CompteContactRoute,
  CompteDashboardRoute: CompteDashboardRoute,
  CompteMesPlatsRoute: CompteMesPlatsRoute,
  CompteRestaurateurRoute: CompteRestaurateurRoute,
  CompteIndexRoute: CompteIndexRoute,
}

const CompteRouteWithChildren =
  CompteRoute._addFileChildren(CompteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CarteRoute: CarteRoute,
  CguRoute: CguRoute,
  CompteRoute: CompteRouteWithChildren,
  ConfidentialiteRoute: ConfidentialiteRoute,
  McpRoute: McpRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PublierRoute: PublierRoute,
  RechercheRoute: RechercheRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  PlatIdRoute: PlatIdRoute,
  ProfilHandleRoute: ProfilHandleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
